### ISSUE TITLE
Players fall through map

### ISSUE THREAD

**Issue by abbeyroad7** [RazrabGit/MAOYSchoolMod#1]
Had an issue where 2 players fell through the map upon entering the main entrance. Not sure if due to this map or custom dungeon.

**Comment by RazrabGit** [comment]
This is probably due to the custom dungeon; I have never seen anything like this after playing with my friends on this moon for quite some time. The time will come, I will port this moon to Lethal Level Loader, as soon as I figure out how to do it, and the custom dungeons will work.
